services:
  darts-matcher-web-development:
    image: darts-matcher-web-development
    container_name: darts-matcher-web-development
    build:
      context: .
      args:
        PROFILE: dev
    restart: unless-stopped
    ports:
      - "4200:80"
