export enum DartboardSection {
  ONE = 'ONE',
  TWO = 'TWO',
  THREE = 'THREE',
  FOUR = 'FOUR',
  FIVE = 'FIVE',
  SIX = 'SIX',
  SEVEN = 'SEVEN',
  EIGHT = 'EIGHT',
  NINE = 'NINE',
  TEN = 'TEN',
  ELEVEN = 'ELEVEN',
  TWELVE = 'TWELVE',
  THIRTEEN = 'THIRTEEN',
  FOURTEEN = 'FOURTEEN',
  FIFTEEN = 'FIFTEEN',
  SIXTEEN = 'SIXTEEN',
  SEVENTEEN = 'SEVENTEEN',
  EIGHTEEN = 'EIGHTEEN',
  NINETEEN = 'NINETEEN',
  TWENTY = 'TWENTY',
  BULL = 'BULL'
}

export const DartboardSectionToNumber: Record<DartboardSection, number> = {
  [DartboardSection.ONE]: 1,
  [DartboardSection.TWO]: 2,
  [DartboardSection.THREE]: 3,
  [DartboardSection.FOUR]: 4,
  [DartboardSection.FIVE]: 5,
  [DartboardSection.SIX]: 6,
  [DartboardSection.SEVEN]: 7,
  [DartboardSection.EIGHT]: 8,
  [DartboardSection.NINE]: 9,
  [DartboardSection.TEN]: 10,
  [DartboardSection.ELEVEN]: 11,
  [DartboardSection.TWELVE]: 12,
  [DartboardSection.THIRTEEN]: 13,
  [DartboardSection.FOURTEEN]: 14,
  [DartboardSection.FIFTEEN]: 15,
  [DartboardSection.SIXTEEN]: 16,
  [DartboardSection.SEVENTEEN]: 17,
  [DartboardSection.EIGHTEEN]: 18,
  [DartboardSection.NINETEEN]: 19,
  [DartboardSection.TWENTY]: 20,
  [DartboardSection.BULL]: 25
};
