export enum X01MatchEventType {
  PROCESS_MATCH = 'PROCESS_MATCH',
  ADD_HUMAN_TURN = 'ADD_HUMAN_TURN',
  ADD_BOT_TURN = 'ADD_BOT_TURN',
  EDIT_TURN = 'EDIT_TURN',
  DELETE_LAST_TURN = 'DELETE_LAST_TURN',
  DELETE_MATCH = 'DELETE_MATCH',
  RESET_MATCH = 'RESET_MATCH',
}
